version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ECR_LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - docker login --username AWS --password $ECR_LOGIN_PASSWORD $ECR_REPOSITORY_URI
  build:
    commands:
      - echo Building frontend Docker image...
      - docker build --build-arg REACT_APP_SERVER_URL=http://stockpriceapp-env.eba-5ps7asta.eu-north-1.elasticbeanstalk.com:8080 -t stock-frontend-docker-image ./apple-stock
      - echo Building backend Docker image...
      - docker build -t stock-backend-docker-image ./apple-stock-backend
  post_build:
    commands:
      - echo Pushing frontend Docker image to Amazon ECR...
      - docker tag stock-frontend-docker-image:latest 878750742588.dkr.ecr.eu-north-1.amazonaws.com/stock-frontend-docker-image:latest
      - docker push 878750742588.dkr.ecr.eu-north-1.amazonaws.com/stock-frontend-docker-image:latest
      - echo Pushing backend Docker image to Amazon ECR...
      - docker tag stock-backend-docker-image:latest 878750742588.dkr.ecr.eu-north-1.amazonaws.com/stock-backend-docker-image:latest
      - docker push 878750742588.dkr.ecr.eu-north-1.amazonaws.com/stock-backend-docker-image:latest